meta_product_name: "MADWORK"
meta_title: "MADWORK - Find Developer Jobs without having to search 50 different
websites"
meta_description: "MADWORK is a scraper that intends
to help developers find job opportunities without having to
search 50 different jobs websites, simply search on MADWORK and we search
all the others for you."
meta_image: "madwork_meta.png" # should exist in `app/assets/images/`
